### ISSUE TITLE
Store the entire JSON message instead of just the content.

### ISSUE THREAD

**Issue by ahdinosaur** [sunrise-choir/flumedb-rs#2]
This will use slightly more disk space but means we don't need to go and hit the offset log for the entire message if needed.

To save some space in the future, we could store the message using cbor and transcode to json if needed.

**Comment by ahdinosaur** [comment]
@pietgeursen i'm curious the reasoning behind this? at first blush it seems silly to store the entire message, when one of the main features of the log is to give us very quick access to the whole message if we need it. i'd be thinking we only want to store in the view what is useful for queries.

**Comment by pietgeursen** [comment]
@ahdinosaur 
> one of the main features of the log is to give us very quick access to the whole message if we need it.

I don't that it _is_ very quick from what I've seen with my benchmarks.
Yes, accessing an item in the offset log is O(1), but because of the 2 system calls (seek and read) to access that O(1) it's really slow and really adds up.

My motivations: 

Soon I want to do benchmarks for `getFeedStream` and if you have to do 2*n sys calls for every message that's gonna really add up. (As yet untested assumption but will compare when I get to it)

**Comment by pietgeursen** [comment]
The api of BufReader has an experimental method [seek_relative](https://doc.rust-lang.org/nightly/std/io/struct.BufReader.html#method.seek_relative) that would help make things more efficient. 

I've avoided using experimental api's but we could just go for it.

**Comment by ahdinosaur** [comment]
yeah, my gut still says we should follow the intended system's design (which is conceptually optimized), then figure out how to optimize the performance.

**Comment by ahdinosaur** [comment]
i'm also curious if any of the performance impact would be different if we were using futures, like if we could read many messages from the log in parallel.

**Comment by pietgeursen** [comment]
Ok, well I'm happy to delay this decision as long as possible.

From the js side as a first pass, if you need an entire message, you'll have to query for sequence numbers and then look them in the log (using the js flume api.) I _think_ this is ok because Dominic has a cache on the log.

**Comment by pietgeursen** [comment]
FYI:
Db only storing content: 425MB
Db storing entire message as JSON: 794MB
Db storing entire message as cbor: 537MB

**Comment by AljoschaMeyer** [comment]
@pietgeursen cbor or clmr?

**Comment by pietgeursen** [comment]
@AljoschaMeyer cbor

I'm having trouble trying to get clmr going. I've spent a couple of hours on it but gonna drop it for now.
Look at the `cant_get_clmr_working` branch if you want to poke around.
When I use `from_compact` for the Multi* I see: "Ctlv(UnexpectedEndOfInput)" at runtime.
When I use `from_legacy` I see "`Err` value: Sigil"

I know the code is not nice but I just wanted to do something fast to get a number for the discussion.

To replicate, edit the bench file to point at your offset log and run `cargo bench`

**Comment by pietgeursen** [comment]
Closing because the db schema is much clearer now and there's no need to store the entire message.
